package domain;

public enum MessageType {
    REGISTRATION,
    REGISTRATION_ERROR,
    AUTHORIZATION,
    AUTH_ERROR,
    SERVER_CATALOG,
    SERVER_CATALOG_UP,
    SERVER_CATALOG_SHOW_SELECTED,
    FILE_COPY,
    FILE_COPY_ACCEPT,
    FILE_COPY_REJECT,
    FILE_COPY_FROM_SERVER,
    FILE_COPY_COMPLETE
}
